.env.sample
docker-compose.yml

As per the docs best practice https://docs.obol.tech/docs/next/int/quickstart/advanced/quickstart-builder-api#validator-clients 
It's present in lodestar/run.sh but not set anywhere I can see

Set the BUILDER_SELECTION env var

---

docker-compose.yml

The docker compose file has an indentation / parsing error and will not work in the current form. 
The fix is a simple space.

Update docker-compose.yml - Fix indendation issue

---

docker-compose.yml

The current version of the main `docker-compose.yml` file has a syntax error, resulting in docker failing to parse the file ( `parsing /home/admin/lido-charon-distributed-validator-node/docker-compose.yml: yaml: line 175: did not find expected key` ).
Introduced in #4 .

Add missing space to docker-compose.yml

---

.env.sample
docker-compose.yml

Allows configuring beacon node on lido-dv-exit and validator-ejector via .env.
Also allow to configure execution node url on validator-ejector .env.

*: export beacon node, execution node URLs for validator-ejector and lido-dv-exit

---

.env.sample
docker-compose.yml

Update .env comment to reflect that as well, and use v0.18.0 as default in docker-compose.yml.

docker-compose: update charon to v0.18.0

---

docker-compose.yml

Use latest available git tag rather than `latest`.
This way operators will update it on restart as well without having to run `docker pull` manually.

docker-compose: fix lido-dv-exit tag

---

docker-compose.yml
grafana/dashboards/validator_ejector_overview.json
prometheus/prometheus.yml

Use version 1.3.0 which includes some fixes.
Also explicitly set HTTP_PORT env var on validator-ejector to fix docker healthcheck, and properly push validator-ejector metrics.

docker-compose: update validator-ejector

---

compose-debug.yml

If configured, push lido-dv-exit log to the configured `CHARON_LOKI_ADDRESSES` instances.
Re-use charon's loki variable so that both are always in sync.

compose-debug: explicitly push lido-dv-exit loki logs

---

prometheus/prometheus.yml

Remnant of yesterday's shenaningans with prometheus.
Revert to previous, known-working configuration.

prometheus: don't explicitly push validator-ejector metrics

---

.env.sample
docker-compose.yml

Easier to toggle than the whole debug setup.

docker-compose: put lido-dv-exit log in env

---

docker-compose.yml

This charon version uses enables two featureset changes to allow for better consensus execution, as well as adding a Lodestar-related interaction workaround.

docker-compose: use lido-specific charon

---

docker-compose.yml

Fixes an issue with clusters for which we have only threshold partial sigs instead of the full set.

docker-compose: update to lido-dv-exit 20d28fd

---

.env.sample
docker-compose.yml

Update clients to support upcoming dencun fork on sepolia and holesky testnets.
https://blog.ethereum.org/2024/01/24/sepolia-holesky-dencun
ticket: https://github.com/ObolNetwork/charon-distributed-validator-node/issues/249

update clients for dencun on holesky

---

docker-compose.yml

Versions updated as follows:
- nethermind: v1.25.3 -> v1.25.4
- lighthouse: v4.6.0 -> v5.0.0 
- lodestar: v1.15.0 -> v1.16.0
- mevboost: 1.6 -> 1.7

docker-compose: update for dencun

---

.env.sample
.env.sample.mainnet
docker-compose.yml

When declaring a port mapping without specifying an IP address Docker defaults to `0.0.0.0` and overrides existing `iptables` rules making these ports accessible to the internet. 
While it is possible to disable this behaviour by specifying `iptables: false` in `/etc/docker/daemon.json` this often results in undesirable connectivity issues as described in the docs here - [Prevent Docker from manipulating iptables](https://docs.docker.com/network/packet-filtering-firewalls/#prevent-docker-from-manipulating-iptables)
This PR restricts access to the Nethermind RPC, Engine API and Grafana dashboard to `127.0.0.1` unless the associated variables are set in `.env`. 
This does not affect connectivity between containers when referencing by container name.

Docker: Exposed Ports Fix

---

.env.sample.holesky
README.md
docker-compose.yml

This means the containers will fail to start if you don't copy a sample env var and hope for the best, because docker will input empty strings for these values, which will not be compatible with the containers.

Moving away from a holesky default

---

docker-compose.yml
grafana/dashboards/dash_charon_overview.json
prometheus/prometheus.yml

Update grafana with the latest version off CDVN, also make prometheus track Nethermind.
Bind grafana container to 0.0.0.0 by default, since operators need to access it from the host system.
More advanced operators can still edit the grafana bind IP with the `MONITORING_IP_GRAFANA` environment variable.

*: update/fix Grafana boards

---

docker-compose.override.yml.sample
lodestar/run.sh

Until charon v1 is released, produce block v3 needs to be turned off.

Turn off produce block v3

---

.env.sample.holesky
.env.sample.mainnet
docker-compose.yml
lodestar/run.sh
relay/docker-compose.yml

Bump charon version to v1.0.0-rc2.
Remove the `useProduceBlockV3` flag from Lodestar.

*: bump charon to v1.0.0-rc2

---

.env.sample.holesky
.env.sample.mainnet
docker-compose.yml
relay/docker-compose.yml

This is for holesky wave users first. Instructions will be given to mainnet operators on when to upgrade separately.

Bump to charon `v1.0.0-rc3`

---

lodestar/run.sh

The env variables we had for builder in docker-compose were never used, as they were overwritten in the shell script...

Remove env vars binding in lodestar run.sh

---

docker-compose.yml
lodestar/run.sh

Some changes imported from CDVN:
- [make lodestar POSIX compliant](https://github.com/ObolNetwork/charon-distributed-validator-node/pull/277)
- [switch to `builderalways` on lodestar](https://github.com/ObolNetwork/charon-distributed-validator-node/pull/274)
- [speed up lodestar key import](https://github.com/ObolNetwork/charon-distributed-validator-node/pull/273)
- move to `unless-stopped` as restart policy for lido-dv-exit

*: sync up with CDVN

---

docker-compose.yml

Bump charon version to v1.1.0. Bump also Lighthouse to v5.3.0 and Lodestar to v1.20.2 - versions with which charon v1.1.0 was tested.

Bump charon to v1.1.0

---

.github/workflows/test.yml
README.md
docker-compose.yml
logging.yml

- Collecting logs from operators when there is an issue takes a long time and is the most labour intensive part of diagnosing an issue with the cluster
- We want to give operators a choice about what they share with Obol when it comes to their data
This PR moves promtail to a second compose file, so operators can opt to run it by changing their `docker compose up -d` command to `docker compose -f docker-compose.yml -f logging.yml up -d`.

Move logging to second file so its opt-in

---

.env.sample.holesky
.env.sample.hoodi
.env.sample.mainnet
docker-compose.yml

950ms is a long time to waste on a hanging request, but modifying the value requires changes to docker compose. 
This PR adds .env vars that can be used to override the default timeouts on mev-boost, without causing future git conflicts.

Paramaterise mev boost timeouts

---

.env.sample.hoodi
docker-compose.yml

This pull request updates the MEV-Boost relays and upgrades the MEV-Boost version to 1.9rc3.
- Updated the list of MEV-Boost relays to align with the latest Lido approved [list](https://enchanted-direction-844.notion.site/6d369eb33f664487800b0dedfe32171e?v=1bdbf633d0c980ddb2c3000ce3c37311).
- Bumped the MEV-Boost version to 1.9rc3.

Update MEV-Boost relays and bump MEV-Boost version to 1.9rc3

---

docker-compose.yml

v1.3.3 handles older versions of charon (v1.3.1 and below) more gracefully than v1.3.2 does. This patch allows clusters to upgrade less synchronously than they would otherwise need to.

Update charon to v1.3.3

---

docker-compose.yml

Updates lido-dv-exit sidecar to depend on charon v1.4.3

Bump lido dv exit

---

docker-compose.yml

After mev-boost introduced `x-timeout-ms` in `1.10a3`, we can safely reduce the timeout for get header.

reduce get header timeout
